/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/vagrant/nim-0.17.2/lib -o /vagrant/bin_python/nimcache/cli_avg.o /vagrant/bin_python/nimcache/cli_avg.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence_Zj5xKXgsXnI4n4hPS6nACA tySequence_Zj5xKXgsXnI4n4hPS6nACA;
typedef struct tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q;
typedef struct tyObject_Data_kyiO0wFzVau9aeEeXTsq9cGQ tyObject_Data_kyiO0wFzVau9aeEeXTsq9cGQ;
typedef struct tySequence_PSP8snSsRoFs9cDiya9bd7UQ tySequence_PSP8snSsRoFs9cDiya9bd7UQ;
typedef struct tyObject_OrderedTable_AF39bJ7XDr6gpANuGpxkHrw tyObject_OrderedTable_AF39bJ7XDr6gpANuGpxkHrw;
typedef struct tySequence_MlAD6nAPq9bHKla9cWiIZP0g tySequence_MlAD6nAPq9bHKla9cWiIZP0g;
typedef struct tySequence_oLpBKXzW3hF9aCVMo5EymfQ tySequence_oLpBKXzW3hF9aCVMo5EymfQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_JsonKindError_oHHjSiHLXjq59bJXBxrX6xQ tyObject_JsonKindError_oHHjSiHLXjq59bJXBxrX6xQ;
typedef struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tySequence_qwqHTkRvwhrRyENtudHQ7g tySequence_qwqHTkRvwhrRyENtudHQ7g;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tyTuple_awOivLjlO76sGdHY7nQUjQ tyTuple_awOivLjlO76sGdHY7nQUjQ;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tySet_tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg;
struct tyObject_Data_kyiO0wFzVau9aeEeXTsq9cGQ {
tySequence_PSP8snSsRoFs9cDiya9bd7UQ* matrix;
};
typedef NU8 tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg;
struct tyObject_OrderedTable_AF39bJ7XDr6gpANuGpxkHrw {
tySequence_MlAD6nAPq9bHKla9cWiIZP0g* data;
NI counter;
NI first;
NI last;
};
struct tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q {
tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg kind;
union{
struct {NimStringDesc* str;
} S1;
struct {NI64 num;
} S2;
struct {NF fnum;
} S3;
struct {NIM_BOOL bval;
} S4;
struct {tyObject_OrderedTable_AF39bJ7XDr6gpANuGpxkHrw fields;
} S6;
struct {tySequence_oLpBKXzW3hF9aCVMo5EymfQ* elems;
} S7;
} kindU;
};
typedef NimStringDesc* tyArray_24KAM9afIUgUaqBaEBB6r9bg[3];
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
Exception* up;
};
struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA {
  Exception Sup;
};
struct tyObject_JsonKindError_oHHjSiHLXjq59bJXBxrX6xQ {
  tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA Sup;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tyTuple_awOivLjlO76sGdHY7nQUjQ {
NI Field0;
NI Field1;
NimStringDesc* Field2;
tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* Field3;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_Zj5xKXgsXnI4n4hPS6nACA {
  TGenericSeq Sup;
  NF data[SEQ_DECL_SIZE];
};
struct tySequence_qwqHTkRvwhrRyENtudHQ7g {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
struct tySequence_PSP8snSsRoFs9cDiya9bd7UQ {
  TGenericSeq Sup;
  tySequence_qwqHTkRvwhrRyENtudHQ7g* data[SEQ_DECL_SIZE];
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_MlAD6nAPq9bHKla9cWiIZP0g {
  TGenericSeq Sup;
  tyTuple_awOivLjlO76sGdHY7nQUjQ data[SEQ_DECL_SIZE];
};
struct tySequence_oLpBKXzW3hF9aCVMo5EymfQ {
  TGenericSeq Sup;
  tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* data[SEQ_DECL_SIZE];
};
N_NIMCALL(NimStringDesc*, dollar__uIHyx8uomwdyfTIUsEo7Bw)(tySet_tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg x);
N_NIMCALL(NimStringDesc*, collectionToString_2oiRPCFIKghA9cdsDSsjiVA)(tySet_tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg x, NimStringDesc* b, NimStringDesc* e);
N_NIMCALL(NI, sum_gbIPXmHbH9cB6gW9ceVVFvbQ)(NI* x, NI xLen_0);
N_NIMCALL(tySequence_Zj5xKXgsXnI4n4hPS6nACA*, main_VZZaTbV4S2u3nRp5Nt5btg)(void);
N_NIMCALL(NI, paramCount_T74rCHY8RMV0X07YnKmggw)(void);
N_NIMCALL(void, quit_y2WuTG82qH44FHhQsKXOCg)(NimStringDesc* errormsg, NI errorcode) __attribute__((noreturn));
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, nosgetAppFilename)(void);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, paramStr_eYicl3uwirn1ppNz7OCowg)(NI i);
N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, parseJson_q2jt59czHU4BW88Mb7EJDUA)(NimStringDesc* buffer);
N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr, NimStringDesc** a, NI aLen_0);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NimStringDesc*, reprEnum)(NI e, TNimType* typ);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
static N_NIMCALL(void, Marker_tySequence_qwqHTkRvwhrRyENtudHQ7g)(void* p, NI op);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence_PSP8snSsRoFs9cDiya9bd7UQ)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
static N_INLINE(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, X5BX5D__bm6Lzuv1zmaV42IeMuikggjson)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* node, NimStringDesc* name);
N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q**, X5BX5D__9bcSZUFhwESDEYXhkxOm8Hg)(tyObject_OrderedTable_AF39bJ7XDr6gpANuGpxkHrw* t, NimStringDesc* key);
N_NOINLINE(void, raiseFieldError)(NimStringDesc* f);
N_NIMCALL(NI, len_1r8KCEmq7uHhZ2GR9c7tsOA_2)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* n);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, X5BX5D__xDCGOmTeHqy9c9aFn6etpytwjson)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* node, NI index);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
static N_NIMCALL(void, Marker_tySequence_Zj5xKXgsXnI4n4hPS6nACA)(void* p, NI op);
static N_INLINE(NF, slash__fu0hCFNNw3xnGgcs2KwTWgsystem)(NI x, NI y);
static N_NIMCALL(void, TM_z7csSM4KAKc9bj3QZB2qXCw_20)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_NIMCALL(void, TM_z7csSM4KAKc9bj3QZB2qXCw_21)(void);
N_NIMCALL(NimStringDesc*, nsuJoinSep)(NimStringDesc** a, NI aLen_0, NimStringDesc* sep);
static N_NIMCALL(void, TM_z7csSM4KAKc9bj3QZB2qXCw_22)(void);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_NIMCALL(NimStringDesc*, nimFloatToStr)(NF f);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_lexbaseInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_lexbaseDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_jsonInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_jsonDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, cli_avgDatInit000)(void);
extern TNimType NTI_RUngo7nCHe6O8aBGIcrhtg_;
extern TNimType NTI_SqAAs0F3YVhfUCIJ3u6KuA_;
extern TNimType NTI_oHHjSiHLXjq59bJXBxrX6xQ_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI_qwqHTkRvwhrRyENtudHQ7g_;
TNimType NTI_PSP8snSsRoFs9cDiya9bd7UQ_;
extern TNimType NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_;
TNimType NTI_Zj5xKXgsXnI4n4hPS6nACA_;
tySequence_Zj5xKXgsXnI4n4hPS6nACA* valSeq_p6kArBMNuXgXr3JeLFCk6w;
NimStringDesc* strings_CDWG9bZA8ey49aPW3dE9a8zOg;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* result_R2pxGLGG0fOT9aep42AlU0w;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
NF it_vlNowW7x6Kg9bNLUK9cbNVVQ;
STRING_LITERAL(TM_z7csSM4KAKc9bj3QZB2qXCw_2, "Usage: ", 7);
STRING_LITERAL(TM_z7csSM4KAKc9bj3QZB2qXCw_3, " {\"matrix\": [[1,2,3], [3,4,5,5]]}", 33);
STRING_LITERAL(TM_z7csSM4KAKc9bj3QZB2qXCw_4, "Incorrect JSON kind. Wanted \'$1\' in \'$2\' but got \'$3\'.", 54);
STRING_LITERAL(TM_z7csSM4KAKc9bj3QZB2qXCw_5, "jsonNode", 8);
STRING_LITERAL(TM_z7csSM4KAKc9bj3QZB2qXCw_6, "not isNil(node) ", 16);
STRING_LITERAL(TM_z7csSM4KAKc9bj3QZB2qXCw_7, "node.kind == JObject ", 21);
STRING_LITERAL(TM_z7csSM4KAKc9bj3QZB2qXCw_8, "fields", 6);
STRING_LITERAL(TM_z7csSM4KAKc9bj3QZB2qXCw_9, "matrix", 6);
STRING_LITERAL(TM_z7csSM4KAKc9bj3QZB2qXCw_10, "jsonNode[\"matrix\"]", 18);
STRING_LITERAL(TM_z7csSM4KAKc9bj3QZB2qXCw_11, "node.kind == JArray ", 20);
STRING_LITERAL(TM_z7csSM4KAKc9bj3QZB2qXCw_12, "elems", 5);
STRING_LITERAL(TM_z7csSM4KAKc9bj3QZB2qXCw_13, "jsonNode[\"matrix\"][i264017]", 27);
STRING_LITERAL(TM_z7csSM4KAKc9bj3QZB2qXCw_14, "jsonNode[\"matrix\"][i264017][i264018]", 36);
STRING_LITERAL(TM_z7csSM4KAKc9bj3QZB2qXCw_15, "num", 3);
STRING_LITERAL(TM_z7csSM4KAKc9bj3QZB2qXCw_19, "len(a) == L seq modified while iterating over it", 48);
STRING_LITERAL(TM_z7csSM4KAKc9bj3QZB2qXCw_24, ",", 1);
STRING_LITERAL(TM_z7csSM4KAKc9bj3QZB2qXCw_25, "[", 1);
STRING_LITERAL(TM_z7csSM4KAKc9bj3QZB2qXCw_26, "]", 1);

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(138, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(216, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(255, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(257, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(258, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(196, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(223, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(224, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(269, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(378, "system.nim");
		nimln_(269, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(270, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(378, "system.nim");
		nimln_(270, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(271, "gc.nim");
	(*dest) = src;
	popFrame();
}
static N_NIMCALL(void, Marker_tySequence_qwqHTkRvwhrRyENtudHQ7g)(void* p, NI op) {
	tySequence_qwqHTkRvwhrRyENtudHQ7g* a;
	NI T1_;
	a = (tySequence_qwqHTkRvwhrRyENtudHQ7g*)p;
	T1_ = (NI)0;
}
static N_NIMCALL(void, Marker_tySequence_PSP8snSsRoFs9cDiya9bd7UQ)(void* p, NI op) {
	tySequence_PSP8snSsRoFs9cDiya9bd7UQ* a;
	NI T1_;
	a = (tySequence_PSP8snSsRoFs9cDiya9bd7UQ*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_], op);
	}
}

static N_INLINE(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, X5BX5D__bm6Lzuv1zmaV42IeMuikggjson)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* node, NimStringDesc* name) {
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* result;
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q** T9_;
	nimfr_("[]", "json.nim");
	result = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
	nimln_(880, "json.nim");
	{
		if (!!(!((node == 0)))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_z7csSM4KAKc9bj3QZB2qXCw_6));
	}
	LA3_: ;
	nimln_(881, "json.nim");
	{
		if (!!(((*node).kind == ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 5)))) goto LA7_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_z7csSM4KAKc9bj3QZB2qXCw_7));
	}
	LA7_: ;
	nimln_(884, "json.nim");
	if (!(((32 &(1U<<((NU)((*node).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_z7csSM4KAKc9bj3QZB2qXCw_8));
	T9_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q**)0;
	T9_ = X5BX5D__9bcSZUFhwESDEYXhkxOm8Hg((&(*node).kindU.S6.fields), name);
	result = (*T9_);
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, X5BX5D__xDCGOmTeHqy9c9aFn6etpytwjson)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* node, NI index) {
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* result;
	nimfr_("[]", "json.nim");
{	result = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
	nimln_(890, "json.nim");
	{
		if (!!(!((node == 0)))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_z7csSM4KAKc9bj3QZB2qXCw_6));
	}
	LA3_: ;
	nimln_(891, "json.nim");
	{
		if (!!(((*node).kind == ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 6)))) goto LA7_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_z7csSM4KAKc9bj3QZB2qXCw_11));
	}
	LA7_: ;
	nimln_(892, "json.nim");
	if (!(((64 &(1U<<((NU)((*node).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_z7csSM4KAKc9bj3QZB2qXCw_12));
	if ((NU)(index) >= (NU)((*node).kindU.S7.elems->Sup.len)) raiseIndexError();
	result = (*node).kindU.S7.elems->data[index];
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}
static N_NIMCALL(void, Marker_tySequence_Zj5xKXgsXnI4n4hPS6nACA)(void* p, NI op) {
	tySequence_Zj5xKXgsXnI4n4hPS6nACA* a;
	NI T1_;
	a = (tySequence_Zj5xKXgsXnI4n4hPS6nACA*)p;
	T1_ = (NI)0;
}

static N_INLINE(NF, slash__fu0hCFNNw3xnGgcs2KwTWgsystem)(NI x, NI y) {
	NF result;
	nimfr_("/", "system.nim");
	result = (NF)0;
	nimln_(3384, "system.nim");
	result = ((NF)(((double) (x))) / (NF)(((double) (y))));
	popFrame();
	return result;
}

N_NIMCALL(tySequence_Zj5xKXgsXnI4n4hPS6nACA*, main_VZZaTbV4S2u3nRp5Nt5btg)(void) {
	tySequence_Zj5xKXgsXnI4n4hPS6nACA* result;
	nimfr_("main", "cli_avg.nim");
{	result = (tySequence_Zj5xKXgsXnI4n4hPS6nACA*)0;
	nimln_(12, "cli_avg.nim");
	{
		NI T3_;
		NimStringDesc* T6_;
		NimStringDesc* T7_;
		nimln_(378, "system.nim");
		nimln_(12, "cli_avg.nim");
		T3_ = (NI)0;
		T3_ = paramCount_T74rCHY8RMV0X07YnKmggw();
		if (!!((T3_ == ((NI) 1)))) goto LA4_;
		nimln_(13, "cli_avg.nim");
		T6_ = (NimStringDesc*)0;
		T7_ = (NimStringDesc*)0;
		T7_ = nosgetAppFilename();
		T6_ = rawNewString(T7_->Sup.len + 40);
appendString(T6_, ((NimStringDesc*) &TM_z7csSM4KAKc9bj3QZB2qXCw_2));
appendString(T6_, T7_);
appendString(T6_, ((NimStringDesc*) &TM_z7csSM4KAKc9bj3QZB2qXCw_3));
		quit_y2WuTG82qH44FHhQsKXOCg(T6_, ((NI) 1));
	}
	goto LA1_;
	LA4_: ;
	{
		NimStringDesc* matrixStr;
		tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* jsonNode;
		tyObject_Data_kyiO0wFzVau9aeEeXTsq9cGQ data;
		tyObject_Data_kyiO0wFzVau9aeEeXTsq9cGQ res;
		tyObject_Data_kyiO0wFzVau9aeEeXTsq9cGQ T15_;
		tySequence_PSP8snSsRoFs9cDiya9bd7UQ* list;
		tySequence_Zj5xKXgsXnI4n4hPS6nACA* res_4;
		nimln_(15, "cli_avg.nim");
		matrixStr = paramStr_eYicl3uwirn1ppNz7OCowg(((NI) 1));
		nimln_(17, "cli_avg.nim");
		jsonNode = parseJson_q2jt59czHU4BW88Mb7EJDUA(matrixStr);
		memset((void*)(&data), 0, sizeof(data));
		nimln_(18, "cli_avg.nim");
		nimln_(1538, "json.nim");
		{
			NimStringDesc* msg;
			tyArray_24KAM9afIUgUaqBaEBB6r9bg T13_;
			tyObject_JsonKindError_oHHjSiHLXjq59bJXBxrX6xQ* e;
			NimStringDesc* T14_;
			nimln_(1167, "system.nim");
			nimln_(1538, "json.nim");
			if (!!(((32 &(1U<<((NU)((*jsonNode).kind)&7U)))!=0))) goto LA11_;
			nimln_(1329, "json.nim");
			memset((void*)T13_, 0, sizeof(T13_));
			nimln_(1538, "json.nim");
			T13_[0] = dollar__uIHyx8uomwdyfTIUsEo7Bw(32);
			T13_[1] = copyString(((NimStringDesc*) &TM_z7csSM4KAKc9bj3QZB2qXCw_5));
			nimln_(1332, "json.nim");
			T13_[2] = copyString(reprEnum((NI)(*jsonNode).kind, (&NTI_RUngo7nCHe6O8aBGIcrhtg_)));
			msg = nsuFormatOpenArray(((NimStringDesc*) &TM_z7csSM4KAKc9bj3QZB2qXCw_4), T13_, 3);
			e = (tyObject_JsonKindError_oHHjSiHLXjq59bJXBxrX6xQ*)0;
			nimln_(2702, "system.nim");
			e = (tyObject_JsonKindError_oHHjSiHLXjq59bJXBxrX6xQ*) newObj((&NTI_SqAAs0F3YVhfUCIJ3u6KuA_), sizeof(tyObject_JsonKindError_oHHjSiHLXjq59bJXBxrX6xQ));
			(*e).Sup.Sup.Sup.m_type = (&NTI_oHHjSiHLXjq59bJXBxrX6xQ_);
			nimln_(1334, "json.nim");
			T14_ = (NimStringDesc*)0;
			T14_ = (*e).Sup.Sup.message; (*e).Sup.Sup.message = copyStringRC1(msg);
			if (T14_) nimGCunrefNoCycle(T14_);
			nimln_(2697, "system.nim");
			asgnRef((void**) (&(*e).Sup.Sup.parent), NIM_NIL);
			nimln_(1334, "json.nim");
			raiseException((Exception*)e, "JsonKindError");
		}
		LA11_: ;
		memset((void*)(&res), 0, sizeof(res));
		nimln_(1722, "json.nim");
		memset((void*)(&T15_), 0, sizeof(T15_));
		memset((void*)(&T15_), 0, sizeof(T15_));
		res.matrix = T15_.matrix;
		nimln_(1616, "json.nim");
		nimln_(1618, "json.nim");
		list = (tySequence_PSP8snSsRoFs9cDiya9bd7UQ*) newSeq((&NTI_PSP8snSsRoFs9cDiya9bd7UQ_), 0);
		nimln_(1619, "json.nim");
		{
			tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T18_;
			NimStringDesc* msg_2;
			tyArray_24KAM9afIUgUaqBaEBB6r9bg T21_;
			tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T22_;
			tyObject_JsonKindError_oHHjSiHLXjq59bJXBxrX6xQ* e_2;
			NimStringDesc* T23_;
			nimln_(1167, "system.nim");
			nimln_(1619, "json.nim");
			nimln_(18, "cli_avg.nim");
			T18_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
			T18_ = X5BX5D__bm6Lzuv1zmaV42IeMuikggjson(jsonNode, ((NimStringDesc*) &TM_z7csSM4KAKc9bj3QZB2qXCw_9));
			if (!!(((64 &(1U<<((NU)((*T18_).kind)&7U)))!=0))) goto LA19_;
			nimln_(1329, "json.nim");
			memset((void*)T21_, 0, sizeof(T21_));
			nimln_(1619, "json.nim");
			T21_[0] = dollar__uIHyx8uomwdyfTIUsEo7Bw(64);
			T21_[1] = copyString(((NimStringDesc*) &TM_z7csSM4KAKc9bj3QZB2qXCw_10));
			nimln_(1332, "json.nim");
			nimln_(18, "cli_avg.nim");
			T22_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
			T22_ = X5BX5D__bm6Lzuv1zmaV42IeMuikggjson(jsonNode, ((NimStringDesc*) &TM_z7csSM4KAKc9bj3QZB2qXCw_9));
			T21_[2] = copyString(reprEnum((NI)(*T22_).kind, (&NTI_RUngo7nCHe6O8aBGIcrhtg_)));
			msg_2 = nsuFormatOpenArray(((NimStringDesc*) &TM_z7csSM4KAKc9bj3QZB2qXCw_4), T21_, 3);
			e_2 = (tyObject_JsonKindError_oHHjSiHLXjq59bJXBxrX6xQ*)0;
			nimln_(2702, "system.nim");
			e_2 = (tyObject_JsonKindError_oHHjSiHLXjq59bJXBxrX6xQ*) newObj((&NTI_SqAAs0F3YVhfUCIJ3u6KuA_), sizeof(tyObject_JsonKindError_oHHjSiHLXjq59bJXBxrX6xQ));
			(*e_2).Sup.Sup.Sup.m_type = (&NTI_oHHjSiHLXjq59bJXBxrX6xQ_);
			nimln_(1334, "json.nim");
			T23_ = (NimStringDesc*)0;
			T23_ = (*e_2).Sup.Sup.message; (*e_2).Sup.Sup.message = copyStringRC1(msg_2);
			if (T23_) nimGCunrefNoCycle(T23_);
			nimln_(2697, "system.nim");
			asgnRef((void**) (&(*e_2).Sup.Sup.parent), NIM_NIL);
			nimln_(1334, "json.nim");
			raiseException((Exception*)e_2, "JsonKindError");
		}
		LA19_: ;
		{
			NI i;
			NI colontmp_;
			tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T25_;
			NI T26_;
			NI res_2;
			i = (NI)0;
			colontmp_ = (NI)0;
			nimln_(1620, "json.nim");
			nimln_(1616, "json.nim");
			nimln_(18, "cli_avg.nim");
			T25_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
			T25_ = X5BX5D__bm6Lzuv1zmaV42IeMuikggjson(jsonNode, ((NimStringDesc*) &TM_z7csSM4KAKc9bj3QZB2qXCw_9));
			T26_ = (NI)0;
			T26_ = len_1r8KCEmq7uHhZ2GR9c7tsOA_2(T25_);
			colontmp_ = subInt(T26_, 1);
			nimln_(1986, "system.nim");
			res_2 = ((NI) 0);
			{
				nimln_(1987, "system.nim");
				while (1) {
					tySequence_qwqHTkRvwhrRyENtudHQ7g* list_2;
					NI T61_;
					NI TM_z7csSM4KAKc9bj3QZB2qXCw_17;
					if (!(res_2 <= colontmp_)) goto LA28;
					nimln_(1988, "system.nim");
					i = res_2;
					nimln_(1620, "json.nim");
					nimln_(1618, "json.nim");
					list_2 = (tySequence_qwqHTkRvwhrRyENtudHQ7g*) newSeq((&NTI_qwqHTkRvwhrRyENtudHQ7g_), 0);
					nimln_(1619, "json.nim");
					{
						tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T31_;
						tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T32_;
						NimStringDesc* msg_3;
						tyArray_24KAM9afIUgUaqBaEBB6r9bg T35_;
						tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T36_;
						tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T37_;
						tyObject_JsonKindError_oHHjSiHLXjq59bJXBxrX6xQ* e_3;
						NimStringDesc* T38_;
						nimln_(1167, "system.nim");
						nimln_(1619, "json.nim");
						nimln_(9, "cli_avg.nim");
						nimln_(18, "cli_avg.nim");
						T31_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
						T31_ = X5BX5D__bm6Lzuv1zmaV42IeMuikggjson(jsonNode, ((NimStringDesc*) &TM_z7csSM4KAKc9bj3QZB2qXCw_9));
						T32_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
						T32_ = X5BX5D__xDCGOmTeHqy9c9aFn6etpytwjson(T31_, i);
						if (!!(((64 &(1U<<((NU)((*T32_).kind)&7U)))!=0))) goto LA33_;
						nimln_(1329, "json.nim");
						memset((void*)T35_, 0, sizeof(T35_));
						nimln_(1619, "json.nim");
						T35_[0] = dollar__uIHyx8uomwdyfTIUsEo7Bw(64);
						T35_[1] = copyString(((NimStringDesc*) &TM_z7csSM4KAKc9bj3QZB2qXCw_13));
						nimln_(1332, "json.nim");
						nimln_(9, "cli_avg.nim");
						nimln_(18, "cli_avg.nim");
						T36_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
						T36_ = X5BX5D__bm6Lzuv1zmaV42IeMuikggjson(jsonNode, ((NimStringDesc*) &TM_z7csSM4KAKc9bj3QZB2qXCw_9));
						T37_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
						T37_ = X5BX5D__xDCGOmTeHqy9c9aFn6etpytwjson(T36_, i);
						T35_[2] = copyString(reprEnum((NI)(*T37_).kind, (&NTI_RUngo7nCHe6O8aBGIcrhtg_)));
						msg_3 = nsuFormatOpenArray(((NimStringDesc*) &TM_z7csSM4KAKc9bj3QZB2qXCw_4), T35_, 3);
						e_3 = (tyObject_JsonKindError_oHHjSiHLXjq59bJXBxrX6xQ*)0;
						nimln_(2702, "system.nim");
						e_3 = (tyObject_JsonKindError_oHHjSiHLXjq59bJXBxrX6xQ*) newObj((&NTI_SqAAs0F3YVhfUCIJ3u6KuA_), sizeof(tyObject_JsonKindError_oHHjSiHLXjq59bJXBxrX6xQ));
						(*e_3).Sup.Sup.Sup.m_type = (&NTI_oHHjSiHLXjq59bJXBxrX6xQ_);
						nimln_(1334, "json.nim");
						T38_ = (NimStringDesc*)0;
						T38_ = (*e_3).Sup.Sup.message; (*e_3).Sup.Sup.message = copyStringRC1(msg_3);
						if (T38_) nimGCunrefNoCycle(T38_);
						nimln_(2697, "system.nim");
						asgnRef((void**) (&(*e_3).Sup.Sup.parent), NIM_NIL);
						nimln_(1334, "json.nim");
						raiseException((Exception*)e_3, "JsonKindError");
					}
					LA33_: ;
					{
						NI i_2;
						NI colontmp__2;
						tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T40_;
						tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T41_;
						NI T42_;
						NI res_3;
						i_2 = (NI)0;
						colontmp__2 = (NI)0;
						nimln_(1620, "json.nim");
						nimln_(1616, "json.nim");
						nimln_(9, "cli_avg.nim");
						nimln_(18, "cli_avg.nim");
						T40_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
						T40_ = X5BX5D__bm6Lzuv1zmaV42IeMuikggjson(jsonNode, ((NimStringDesc*) &TM_z7csSM4KAKc9bj3QZB2qXCw_9));
						T41_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
						T41_ = X5BX5D__xDCGOmTeHqy9c9aFn6etpytwjson(T40_, i);
						T42_ = (NI)0;
						T42_ = len_1r8KCEmq7uHhZ2GR9c7tsOA_2(T41_);
						colontmp__2 = subInt(T42_, 1);
						nimln_(1986, "system.nim");
						res_3 = ((NI) 0);
						{
							nimln_(1987, "system.nim");
							while (1) {
								tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T57_;
								tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T58_;
								tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T59_;
								NI T60_;
								NI TM_z7csSM4KAKc9bj3QZB2qXCw_16;
								if (!(res_3 <= colontmp__2)) goto LA44;
								nimln_(1988, "system.nim");
								i_2 = res_3;
								nimln_(1620, "json.nim");
								nimln_(1565, "json.nim");
								{
									tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T47_;
									tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T48_;
									tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T49_;
									NimStringDesc* msg_4;
									tyArray_24KAM9afIUgUaqBaEBB6r9bg T52_;
									tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T53_;
									tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T54_;
									tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T55_;
									tyObject_JsonKindError_oHHjSiHLXjq59bJXBxrX6xQ* e_4;
									NimStringDesc* T56_;
									nimln_(1167, "system.nim");
									nimln_(1565, "json.nim");
									nimln_(1470, "json.nim");
									nimln_(9, "cli_avg.nim");
									nimln_(18, "cli_avg.nim");
									T47_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
									T47_ = X5BX5D__bm6Lzuv1zmaV42IeMuikggjson(jsonNode, ((NimStringDesc*) &TM_z7csSM4KAKc9bj3QZB2qXCw_9));
									T48_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
									T48_ = X5BX5D__xDCGOmTeHqy9c9aFn6etpytwjson(T47_, i);
									T49_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
									T49_ = X5BX5D__xDCGOmTeHqy9c9aFn6etpytwjson(T48_, i_2);
									if (!!(((4 &(1U<<((NU)((*T49_).kind)&7U)))!=0))) goto LA50_;
									nimln_(1329, "json.nim");
									memset((void*)T52_, 0, sizeof(T52_));
									nimln_(1565, "json.nim");
									T52_[0] = dollar__uIHyx8uomwdyfTIUsEo7Bw(4);
									T52_[1] = copyString(((NimStringDesc*) &TM_z7csSM4KAKc9bj3QZB2qXCw_14));
									nimln_(1332, "json.nim");
									nimln_(1470, "json.nim");
									nimln_(9, "cli_avg.nim");
									nimln_(18, "cli_avg.nim");
									T53_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
									T53_ = X5BX5D__bm6Lzuv1zmaV42IeMuikggjson(jsonNode, ((NimStringDesc*) &TM_z7csSM4KAKc9bj3QZB2qXCw_9));
									T54_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
									T54_ = X5BX5D__xDCGOmTeHqy9c9aFn6etpytwjson(T53_, i);
									T55_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
									T55_ = X5BX5D__xDCGOmTeHqy9c9aFn6etpytwjson(T54_, i_2);
									T52_[2] = copyString(reprEnum((NI)(*T55_).kind, (&NTI_RUngo7nCHe6O8aBGIcrhtg_)));
									msg_4 = nsuFormatOpenArray(((NimStringDesc*) &TM_z7csSM4KAKc9bj3QZB2qXCw_4), T52_, 3);
									e_4 = (tyObject_JsonKindError_oHHjSiHLXjq59bJXBxrX6xQ*)0;
									nimln_(2702, "system.nim");
									e_4 = (tyObject_JsonKindError_oHHjSiHLXjq59bJXBxrX6xQ*) newObj((&NTI_SqAAs0F3YVhfUCIJ3u6KuA_), sizeof(tyObject_JsonKindError_oHHjSiHLXjq59bJXBxrX6xQ));
									(*e_4).Sup.Sup.Sup.m_type = (&NTI_oHHjSiHLXjq59bJXBxrX6xQ_);
									nimln_(1334, "json.nim");
									T56_ = (NimStringDesc*)0;
									T56_ = (*e_4).Sup.Sup.message; (*e_4).Sup.Sup.message = copyStringRC1(msg_4);
									if (T56_) nimGCunrefNoCycle(T56_);
									nimln_(2697, "system.nim");
									asgnRef((void**) (&(*e_4).Sup.Sup.parent), NIM_NIL);
									nimln_(1334, "json.nim");
									raiseException((Exception*)e_4, "JsonKindError");
								}
								LA50_: ;
								nimln_(1470, "json.nim");
								nimln_(9, "cli_avg.nim");
								nimln_(18, "cli_avg.nim");
								T57_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
								T57_ = X5BX5D__bm6Lzuv1zmaV42IeMuikggjson(jsonNode, ((NimStringDesc*) &TM_z7csSM4KAKc9bj3QZB2qXCw_9));
								T58_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
								T58_ = X5BX5D__xDCGOmTeHqy9c9aFn6etpytwjson(T57_, i);
								T59_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
								T59_ = X5BX5D__xDCGOmTeHqy9c9aFn6etpytwjson(T58_, i_2);
								if (!(((4 &(1U<<((NU)((*T59_).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_z7csSM4KAKc9bj3QZB2qXCw_15));
								list_2 = (tySequence_qwqHTkRvwhrRyENtudHQ7g*) incrSeqV2(&(list_2)->Sup, sizeof(NI));
								T60_ = list_2->Sup.len++;
								list_2->data[T60_] = ((NI) ((*T59_).kindU.S2.num));
								nimln_(1989, "system.nim");
								TM_z7csSM4KAKc9bj3QZB2qXCw_16 = addInt(res_3, ((NI) 1));
								res_3 = (NI)(TM_z7csSM4KAKc9bj3QZB2qXCw_16);
							} LA44: ;
						}
					}
					list = (tySequence_PSP8snSsRoFs9cDiya9bd7UQ*) incrSeqV2(&(list)->Sup, sizeof(tySequence_qwqHTkRvwhrRyENtudHQ7g*));
					T61_ = list->Sup.len++;
					genericSeqAssign((&list->data[T61_]), list_2, (&NTI_qwqHTkRvwhrRyENtudHQ7g_));
					TM_z7csSM4KAKc9bj3QZB2qXCw_17 = addInt(res_2, ((NI) 1));
					res_2 = (NI)(TM_z7csSM4KAKc9bj3QZB2qXCw_17);
				} LA28: ;
			}
		}
		genericSeqAssign((&res.matrix), list, (&NTI_PSP8snSsRoFs9cDiya9bd7UQ_));
		data.matrix = res.matrix;
		nimln_(20, "cli_avg.nim");
		res_4 = (tySequence_Zj5xKXgsXnI4n4hPS6nACA*) newSeq((&NTI_Zj5xKXgsXnI4n4hPS6nACA_), 0);
		{
			tySequence_qwqHTkRvwhrRyENtudHQ7g* vector;
			tySequence_PSP8snSsRoFs9cDiya9bd7UQ* colontmp__3;
			NI i_3;
			NI L;
			NI T63_;
			vector = (tySequence_qwqHTkRvwhrRyENtudHQ7g*)0;
			colontmp__3 = (tySequence_PSP8snSsRoFs9cDiya9bd7UQ*)0;
			nimln_(21, "cli_avg.nim");
			colontmp__3 = data.matrix;
			nimln_(3639, "system.nim");
			i_3 = ((NI) 0);
			nimln_(3640, "system.nim");
			T63_ = (colontmp__3 ? colontmp__3->Sup.len : 0);
			L = T63_;
			{
				nimln_(3641, "system.nim");
				while (1) {
					NI T66_;
					NI T67_;
					NF T68_;
					NI T69_;
					NI TM_z7csSM4KAKc9bj3QZB2qXCw_18;
					if (!(i_3 < L)) goto LA65;
					nimln_(3642, "system.nim");
					if ((NU)(i_3) >= (NU)(colontmp__3->Sup.len)) raiseIndexError();
					vector = colontmp__3->data[i_3];
					nimln_(22, "cli_avg.nim");
					T66_ = (NI)0;
					T66_ = sum_gbIPXmHbH9cB6gW9ceVVFvbQ(vector->data, vector->Sup.len);
					T67_ = (vector ? vector->Sup.len : 0);
					T68_ = (NF)0;
					T68_ = slash__fu0hCFNNw3xnGgcs2KwTWgsystem(T66_, T67_);
					res_4 = (tySequence_Zj5xKXgsXnI4n4hPS6nACA*) incrSeqV2(&(res_4)->Sup, sizeof(NF));
					T69_ = res_4->Sup.len++;
					res_4->data[T69_] = T68_;
					nimln_(3643, "system.nim");
					TM_z7csSM4KAKc9bj3QZB2qXCw_18 = addInt(i_3, ((NI) 1));
					i_3 = (NI)(TM_z7csSM4KAKc9bj3QZB2qXCw_18);
					nimln_(3644, "system.nim");
					{
						NI T72_;
						T72_ = (colontmp__3 ? colontmp__3->Sup.len : 0);
						if (!!((T72_ == L))) goto LA73_;
						failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_z7csSM4KAKc9bj3QZB2qXCw_19));
					}
					LA73_: ;
				} LA65: ;
			}
		}
		nimln_(24, "cli_avg.nim");
		genericSeqAssign((&result), res_4, (&NTI_Zj5xKXgsXnI4n4hPS6nACA_));
		goto BeforeRet_;
	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_NIMCALL(void, TM_z7csSM4KAKc9bj3QZB2qXCw_20)(void) {
	nimGCvisit((void*)valSeq_p6kArBMNuXgXr3JeLFCk6w, 0);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(276, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(378, "system.nim");
		nimln_(276, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(277, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(278, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(279, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(378, "system.nim");
		nimln_(279, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(280, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(281, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(282, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(283, "gc.nim");
	(*dest) = src;
	popFrame();
}
static N_NIMCALL(void, TM_z7csSM4KAKc9bj3QZB2qXCw_21)(void) {
	nimGCvisit((void*)strings_CDWG9bZA8ey49aPW3dE9a8zOg, 0);
}
static N_NIMCALL(void, TM_z7csSM4KAKc9bj3QZB2qXCw_22)(void) {
	nimGCvisit((void*)result_R2pxGLGG0fOT9aep42AlU0w, 0);
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_timesDatInit000();
	stdlib_posixDatInit000();
	stdlib_ospathsDatInit000();
	stdlib_osDatInit000();
	stdlib_hashesDatInit000();
	stdlib_tablesDatInit000();
	stdlib_streamsDatInit000();
	stdlib_lexbaseDatInit000();
	stdlib_unicodeDatInit000();
	stdlib_macrosDatInit000();
	stdlib_jsonDatInit000();
	stdlib_sequtilsDatInit000();
	cli_avgDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_timesInit000();
	stdlib_posixInit000();
	stdlib_ospathsInit000();
	stdlib_osInit000();
	stdlib_hashesInit000();
	stdlib_tablesInit000();
	stdlib_streamsInit000();
	stdlib_lexbaseInit000();
	stdlib_unicodeInit000();
	stdlib_macrosInit000();
	stdlib_jsonInit000();
	stdlib_sequtilsInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	NimStringDesc* T13_;
	nimfr_("cli_avg", "cli_avg.nim");
nimRegisterGlobalMarker(TM_z7csSM4KAKc9bj3QZB2qXCw_20);
nimRegisterGlobalMarker(TM_z7csSM4KAKc9bj3QZB2qXCw_21);
nimRegisterGlobalMarker(TM_z7csSM4KAKc9bj3QZB2qXCw_22);
	nimln_(26, "cli_avg.nim");
	asgnRefNoCycle((void**) (&valSeq_p6kArBMNuXgXr3JeLFCk6w), main_VZZaTbV4S2u3nRp5Nt5btg());
	nimln_(27, "cli_avg.nim");
	nimln_(598, "sequtils.nim");
	if (result_R2pxGLGG0fOT9aep42AlU0w) { nimGCunrefNoCycle(result_R2pxGLGG0fOT9aep42AlU0w); result_R2pxGLGG0fOT9aep42AlU0w = NIM_NIL; }
	result_R2pxGLGG0fOT9aep42AlU0w = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeqRC1((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
	{
		NI i;
		NI L;
		NI T2_;
		nimln_(3639, "system.nim");
		i = ((NI) 0);
		nimln_(3640, "system.nim");
		T2_ = (valSeq_p6kArBMNuXgXr3JeLFCk6w ? valSeq_p6kArBMNuXgXr3JeLFCk6w->Sup.len : 0);
		L = T2_;
		{
			nimln_(3641, "system.nim");
			while (1) {
				NimStringDesc* T5_;
				NI T6_;
				NimStringDesc* T7_;
				NI TM_z7csSM4KAKc9bj3QZB2qXCw_23;
				if (!(i < L)) goto LA4;
				nimln_(3642, "system.nim");
				if ((NU)(i) >= (NU)(valSeq_p6kArBMNuXgXr3JeLFCk6w->Sup.len)) raiseIndexError();
				it_vlNowW7x6Kg9bNLUK9cbNVVQ = valSeq_p6kArBMNuXgXr3JeLFCk6w->data[i];
				nimln_(600, "sequtils.nim");
				nimln_(27, "cli_avg.nim");
				T5_ = (NimStringDesc*)0;
				T5_ = nimFloatToStr(it_vlNowW7x6Kg9bNLUK9cbNVVQ);
				result_R2pxGLGG0fOT9aep42AlU0w = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&(result_R2pxGLGG0fOT9aep42AlU0w)->Sup, sizeof(NimStringDesc*));
				T6_ = result_R2pxGLGG0fOT9aep42AlU0w->Sup.len++;
				T7_ = (NimStringDesc*)0;
				T7_ = result_R2pxGLGG0fOT9aep42AlU0w->data[T6_]; result_R2pxGLGG0fOT9aep42AlU0w->data[T6_] = copyStringRC1(T5_);
				if (T7_) nimGCunrefNoCycle(T7_);
				nimln_(3643, "system.nim");
				TM_z7csSM4KAKc9bj3QZB2qXCw_23 = addInt(i, ((NI) 1));
				i = (NI)(TM_z7csSM4KAKc9bj3QZB2qXCw_23);
				nimln_(3644, "system.nim");
				{
					NI T10_;
					T10_ = (valSeq_p6kArBMNuXgXr3JeLFCk6w ? valSeq_p6kArBMNuXgXr3JeLFCk6w->Sup.len : 0);
					if (!!((T10_ == L))) goto LA11_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_z7csSM4KAKc9bj3QZB2qXCw_19));
				}
				LA11_: ;
			} LA4: ;
		}
	}
	asgnRefNoCycle((void**) (&strings_CDWG9bZA8ey49aPW3dE9a8zOg), nsuJoinSep(result_R2pxGLGG0fOT9aep42AlU0w->data, result_R2pxGLGG0fOT9aep42AlU0w->Sup.len, ((NimStringDesc*) &TM_z7csSM4KAKc9bj3QZB2qXCw_24)));
	nimln_(28, "cli_avg.nim");
	T13_ = (NimStringDesc*)0;
	T13_ = rawNewString(strings_CDWG9bZA8ey49aPW3dE9a8zOg->Sup.len + 2);
appendString(T13_, ((NimStringDesc*) &TM_z7csSM4KAKc9bj3QZB2qXCw_25));
appendString(T13_, strings_CDWG9bZA8ey49aPW3dE9a8zOg);
appendString(T13_, ((NimStringDesc*) &TM_z7csSM4KAKc9bj3QZB2qXCw_26));
	printf("%s\012", T13_? (T13_)->data:"nil");
	fflush(stdout);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, cli_avgDatInit000)(void) {
NTI_qwqHTkRvwhrRyENtudHQ7g_.size = sizeof(tySequence_qwqHTkRvwhrRyENtudHQ7g*);
NTI_qwqHTkRvwhrRyENtudHQ7g_.kind = 24;
NTI_qwqHTkRvwhrRyENtudHQ7g_.base = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
NTI_qwqHTkRvwhrRyENtudHQ7g_.flags = 2;
NTI_qwqHTkRvwhrRyENtudHQ7g_.marker = Marker_tySequence_qwqHTkRvwhrRyENtudHQ7g;
NTI_PSP8snSsRoFs9cDiya9bd7UQ_.size = sizeof(tySequence_PSP8snSsRoFs9cDiya9bd7UQ*);
NTI_PSP8snSsRoFs9cDiya9bd7UQ_.kind = 24;
NTI_PSP8snSsRoFs9cDiya9bd7UQ_.base = (&NTI_qwqHTkRvwhrRyENtudHQ7g_);
NTI_PSP8snSsRoFs9cDiya9bd7UQ_.flags = 2;
NTI_PSP8snSsRoFs9cDiya9bd7UQ_.marker = Marker_tySequence_PSP8snSsRoFs9cDiya9bd7UQ;
NTI_Zj5xKXgsXnI4n4hPS6nACA_.size = sizeof(tySequence_Zj5xKXgsXnI4n4hPS6nACA*);
NTI_Zj5xKXgsXnI4n4hPS6nACA_.kind = 24;
NTI_Zj5xKXgsXnI4n4hPS6nACA_.base = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
NTI_Zj5xKXgsXnI4n4hPS6nACA_.flags = 2;
NTI_Zj5xKXgsXnI4n4hPS6nACA_.marker = Marker_tySequence_Zj5xKXgsXnI4n4hPS6nACA;
}

